### ISSUE TITLE
SM OR - Problem with o:sortAscendingMenuItem and o:sortDescendingMenuItem

### ISSUE THREAD

**Issue by Chasyl** [TeamDev-Ltd/OpenFaces#107]
In Terms Tab -> Double-Click to open any of the dimensions dialog from an existing condition -> Close the pop-up window without modifying anything -> Click any column header
Actual Result: Error message appears
This problem occurs because after sorting a table the entire page is rendered instead of just the parts needed.

**Comment by YurinM** [comment]
Fixed.
