### ISSUE TITLE
SM OR - Tag: "<o:scrolling>" affects dimensions hints presentation.

### ISSUE THREAD

**Issue by ArielHO** [TeamDev-Ltd/OpenFaces#108]
Using "o:scrolling" tag causes dimensions hints not to show expected data.
For example go to: contracts -> terms tab -> groups section -> click once on any column that contains dimensions, the outcome will be:
_____________________________________________________________________________

![capture](https://cloud.githubusercontent.com/assets/10962848/7336748/83d6278c-ec15-11e4-8a0c-b85efd87dad9.JPG)
_____________________________________________________________________________

Instead of:
_____________________________________________________________________________
![capture](https://cloud.githubusercontent.com/assets/10962848/7336754/c507fb90-ec15-11e4-8185-2d315f19135a.JPG)
_____________________________________________________________________________

**Comment by ArielHO** [comment]
This issue is not fixed! therefore it shouldn't be close.

**Comment by YurinM** [comment]
Cannot reproduce this issue.

**Comment by YurinM** [comment]
Fixed.
