### ISSUE TITLE
SM OR - when scrolling grid in dialog all the dialog resized and unnecessary scrolls appear.

### ISSUE THREAD

**Issue by MiriamAssayag** [TeamDev-Ltd/OpenFaces#114]
![unnecessaryscrolls](https://cloud.githubusercontent.com/assets/9367559/7570263/93a918c8-f817-11e4-9ba6-fff10cd93b52.PNG)

**Comment by YurinM** [comment]
This issue fixed in range of a issue https://github.com/TeamDev-Ltd/OpenFaces/issues/134. In the issue, proposed decision with fixed footer layout. Also, modal dialogs setted as unscrollable container.
