### ISSUE TITLE
SM OR - When grid is empty with fixed columns the text is not aligned correct

### ISSUE THREAD

**Issue by DimaSol** [TeamDev-Ltd/OpenFaces#124]
![text not aligned](https://cloud.githubusercontent.com/assets/6746815/7832645/3a4cdfd6-0469-11e5-9f2a-04eec363588f.png)

**Comment by YurinM** [comment]
How I can reproduce this issue? 
On the remote PC i can see another picture: 
![image](https://cloud.githubusercontent.com/assets/6769624/7862985/3118f112-0562-11e5-9a05-eb7d3f44fc9b.png)

**Comment by DimaSol** [comment]
Use "fixed" attribute for the first column

**Comment by YurinM** [comment]
When we use attribute "fixed" for the left column, we actually divide the table body on two tables: 
* left - fixed table (unscrollable)
* center - unfixed table (scrollable).

By default text "No records" aligned by center table body. And after separate table to fixed and scrollable tables, text "No records"  remains in scrollable part of the table. 
So, when we try to align text left - text has aligned by left side of the scrollable table.

As solution, I can add an attribute, using which it will be possible to choose text align type for fixed no data cases.

**Comment by DimaSol** [comment]
Notice that there is also a vertical separation line that shouldn't be there in case that there are no records, also in case that the empty table text is longer than the width of this first column it should be visible similarly to the way that there were no fixed columns at all. If your attribute will handle all this it's seems to be fine, but in this case I don't really see a reason for an attribute as this should be the regular behavior.

**Comment by YurinM** [comment]
Fixed.
