### ISSUE TITLE
SM OR - A problem with <o:selectOneMenu>

### ISSUE THREAD

**Issue by Chasyl** [TeamDev-Ltd/OpenFaces#125]
Try to open any dd list in chrome version 43.0.2357.81 m -> sometimes the dd doesn't open and sometimes it opens but its width is 2px.

![inconsistent dropdown](https://cloud.githubusercontent.com/assets/11959915/7837562/86888112-0490-11e5-85dd-de1a4513a856.PNG)

**Comment by razav** [comment]
will be fixed with issue https://github.com/TeamDev-Ltd/OpenFaces/issues/128

**Comment by YurinM** [comment]
Fixed.
