### ISSUE TITLE
SM OR - problem with <o:selectOneMenu  and <o:closeWindowButton

### ISSUE THREAD

**Issue by razav** [TeamDev-Ltd/OpenFaces#128]
When other components - such as <p:selectCheckboxMenu  are open, and then clicking on the <o:selectOneMenu  or <o:closeWindowButton , the <p:selectCheckboxMenu does not get closed.

when clicking on other components (not open faces) the  <p:selectCheckboxMenu get closed.

please see attached, the already opened dropdown is <p:selectCheckboxMenu , and the second opened is openfaces dropdown

![raz openfaces](https://cloud.githubusercontent.com/assets/10533659/7938571/f3ad1f74-094e-11e5-9a9d-881b74abf050.jpg)

Notice that the problem might happen on other <o: components

**Comment by razav** [comment]
The problem with <o:selectOneMenu is fixed by max but with <o:closeWindowButton the problem still occurs. and there might be more open faces components that will block the primefaces component from closing.

**Comment by razav** [comment]
the problem is fixed also in <o:closeWindowButton but not in <o:window, because when you try to drag the windows the primefaces component stays open.

also , issue : https://github.com/TeamDev-Ltd/OpenFaces/issues/125
is fixed partially , now the dropdown sometimes does not open.

**Comment by YurinM** [comment]
Issue closed. Issue #125 should be fixed separately.
