### ISSUE TITLE
SM OR - An error with floatingIconMessage ids

### ISSUE THREAD

**Issue by Chasyl** [TeamDev-Ltd/OpenFaces#131]
I added a floatingIconMessage to a dateCooser in a dialogForm (I added it by me to TransferRunsDlg.xhtml and you can open this dialog in Terms tab -> Budget and Runs tab -> select a run from runs grid -> Press on Tools -> Transfer Runs) like this:

![image](https://cloud.githubusercontent.com/assets/11959915/8077738/fb7a804e-0f60-11e5-8ac8-cf6a5c619364.png)

But when I do something that causes a render to the message I get an error message:

![floatingiconmessage not found](https://cloud.githubusercontent.com/assets/11959915/8077546/5d471bea-0f5f-11e5-94c3-b7c08f26f7e4.PNG)

Max Yurin knows about this issue.

**Comment by YurinM** [comment]
Fixed.
