### ISSUE TITLE
SM OR - A problem with floatingIconMessage

### ISSUE THREAD

**Issue by Chasyl** [TeamDev-Ltd/OpenFaces#133]
I added a floatingIconMessage to a dateChooser in a dialog:

![floatingicon 1](https://cloud.githubusercontent.com/assets/11959915/8396770/f82ef36a-1dbc-11e5-90a0-1c4385fd7a95.PNG)

And when I scroll down the dialog the icon is seen outside the dialog:

![floatingicon 2](https://cloud.githubusercontent.com/assets/11959915/8396772/fdc55c6a-1dbc-11e5-98a6-9045882cad44.PNG)

Max Yurin knows about this issue.

**Comment by YurinM** [comment]
Fixed.
