### ISSUE TITLE
SM OR - problem with resizing <o:window.

### ISSUE THREAD

**Issue by razav** [TeamDev-Ltd/OpenFaces#134]
In some dialogs with the same style structure , button are overlaying other components.
this does not happen in all dialogs for some reason.

![bug1](https://cloud.githubusercontent.com/assets/10533659/8402962/2e0c4f0a-1e49-11e5-9f9e-751429a8d86e.jpg)

![bug3](https://cloud.githubusercontent.com/assets/10533659/8402964/32e84330-1e49-11e5-86ca-773991d79c0d.jpg)

Also, in the dialogs where it dosent happen, when you resize the window and get to <o:datatable - the buttons start to overlay that component. for example:
![bug2](https://cloud.githubusercontent.com/assets/10533659/8402729/af66f90e-1e46-11e5-8f4d-13433bce3be1.png)

As you see,in this dialog, in the before image , the buttons arent shown - as expected.

**Comment by YurinM** [comment]
Closed. 
Proposed decision with fix of the bottom buttons panel group.
