### ISSUE TITLE
SM OR - Grid display blank when changing counting in group when the dialog opened

### ISSUE THREAD

**Issue by MiriamAssayag** [TeamDev-Ltd/OpenFaces#135]
![blank](https://cloud.githubusercontent.com/assets/9367559/8472984/78ba0c4c-20ae-11e5-83c6-fa1df13f97f0.PNG)

**Comment by MiriamAssayag** [comment]
step to reproduce:
create group with 1 or more runs -> change from condition tab -> change the counting ->
dialog will appear but the tabs will be blank.

**Comment by YurinM** [comment]
Fixed.  There was a problem with NullPointerException in the persistence layer.
