### ISSUE TITLE
SM OR - composite:attribute can't get its value from the server in <o:inputText

### ISSUE THREAD

**Issue by Chasyl** [TeamDev-Ltd/OpenFaces#136]
I added a composite:attribute (- composite:attribute name="isWriteoffOrConversion") to the composite:interface sm:monetaryAmount and I want to set its value from the server - when I used this component I tried setting this attributes value like this:

< sm:monetaryAmount id="updateBudgetAmount"
			value="updateDialogController.updateController.grid.modelValue"
			isWriteoffOrConversion="#{updateDialogController.updateController.isWriteoffOrConversion}" />

 but it does not work, I can set the attributes value only as a fixed value, like this:

< sm:monetaryAmount id="updateBudgetAmount"
			value="updateDialogController.updateController.grid.modelValue"
			isWriteoffOrConversion="true" />

**Comment by YurinM** [comment]
Fixed. There was an issue with jsf bean.
