### ISSUE TITLE
SM OR - when use the attr 'fixed ="true"' in data table the scrolls of the whole grid not appear

### ISSUE THREAD

**Issue by MiriamAssayag** [TeamDev-Ltd/OpenFaces#97]

**Comment by YurinM** [comment]
When used a fixed attribute in a dataTable, the horizontal scroll should be visible only for "scrollable" - not fixed columns. So it\`s possible to exclude one or more columns from horizontal scrolling and fix them on the table\`s left or right side. 
Please read more about the fixed attribute: [DataTable, Content Scrolling](https://github.com/TeamDev-Ltd/OpenFaces/wiki/DataTable-2.x#content-scrolling)

**Comment by YurinM** [comment]
Fixed.
